const v = (color, size, stock) => ({ color, size, stock });

export const sample_products = [
  {
    name: "Nike Air Max 90",
    brand: "Nike",
    gender: "men",
    category: "Sneakers",
    description:
      "Iconic Air cushioning meets timeless street style. The Air Max 90 stays true to its OG running roots with the iconic Waffle sole, stitched overlays and classic TPU details.",
    price: 130,
    images: ["image-1.jpg"],
    tags: ["Sneakers", "Casual"],
    variants: [
      v("Black", 41, 5),
      v("Black", 42, 8),
      v("Black", 43, 4),
      v("Black", 45, 0),
      v("White", 41, 6),
      v("White", 42, 3),
      v("White", 43, 7),
    ],
  },
  {
    name: "Adidas Stan Smith",
    brand: "Adidas",
    gender: "men",
    category: "Sneakers",
    description:
      "A clean court classic. The Stan Smith has stood the test of time as a minimalist tennis shoe turned everyday icon.",
    price: 100,
    images: ["image-1.jpg"],
    tags: ["Sneakers", "Casual"],
    variants: [
      v("White", 39, 4),
      v("White", 40, 6),
      v("White", 41, 5),
      v("White", 42, 7),
      v("Green", 40, 2),
      v("Green", 41, 0),
      v("Green", 42, 3),
    ],
  },
  {
    name: "Converse Chuck 70",
    brand: "Converse",
    gender: "women",
    category: "Sneakers",
    description:
      "A premium take on the original Chuck Taylor. Higher-quality canvas, cushioned insole and vintage detailing.",
    price: 85,
    images: ["image-1.jpg"],
    tags: ["Sneakers", "Casual"],
    variants: [
      v("Black", 37, 3),
      v("Black", 38, 5),
      v("Black", 39, 4),
      v("Cream", 37, 2),
      v("Cream", 38, 0),
      v("Cream", 39, 6),
    ],
  },
  {
    name: "Nike Pegasus 40",
    brand: "Nike",
    gender: "men",
    category: "Running",
    description:
      "A workhorse running shoe with responsive React foam and dual Air Zoom units for a smooth, springy ride.",
    price: 140,
    images: ["image-1.jpg"],
    tags: ["Running", "Sport"],
    variants: [
      v("Blue", 41, 4),
      v("Blue", 42, 6),
      v("Blue", 43, 3),
      v("Black", 41, 2),
      v("Black", 42, 5),
      v("Black", 43, 0),
    ],
  },
  {
    name: "Asics Gel-Kayano 30",
    brand: "Asics",
    gender: "women",
    category: "Running",
    description:
      "Premium stability running shoe with FF BLAST PLUS ECO foam and PureGEL technology for a soft, supported run.",
    price: 165,
    images: ["image-1.jpg"],
    tags: ["Running", "Sport"],
    variants: [
      v("Pink", 38, 3),
      v("Pink", 39, 4),
      v("Pink", 40, 2),
      v("Grey", 38, 5),
      v("Grey", 39, 6),
      v("Grey", 40, 4),
    ],
  },
  {
    name: "Dr. Martens 1460",
    brand: "Dr. Martens",
    gender: "men",
    category: "Boots",
    description:
      "The original 8-eye boot. Smooth leather, yellow welt stitch, and a Goodyear-welted air-cushioned sole.",
    price: 180,
    images: ["image-1.jpg"],
    tags: ["Boots", "Casual"],
    variants: [
      v("Black", 40, 4),
      v("Black", 41, 5),
      v("Black", 42, 3),
      v("Cherry", 40, 2),
      v("Cherry", 41, 0),
      v("Cherry", 42, 4),
    ],
  },
  {
    name: "Timberland 6-Inch Premium",
    brand: "Timberland",
    gender: "men",
    category: "Boots",
    description: "The original yellow boot. Waterproof premium leather, padded collar, seam-sealed construction.",
    price: 210,
    images: ["image-1.jpg"],
    tags: ["Boots"],
    variants: [v("Wheat", 41, 3), v("Wheat", 42, 4), v("Wheat", 43, 2), v("Wheat", 44, 5)],
  },
  {
    name: "Clarks Tilden Cap Oxford",
    brand: "Clarks",
    gender: "men",
    category: "Formal",
    description: "A classic cap-toe oxford in polished leather. Cushioned footbed and rubber sole for all-day comfort.",
    price: 120,
    images: ["image-1.jpg"],
    tags: ["Formal"],
    variants: [
      v("Black", 41, 4),
      v("Black", 42, 5),
      v("Black", 43, 3),
      v("Brown", 41, 2),
      v("Brown", 42, 4),
      v("Brown", 43, 0),
    ],
  },
  {
    name: "Birkenstock Arizona",
    brand: "Birkenstock",
    gender: "women",
    category: "Sandals",
    description:
      "Two-strap classic with the famous contoured cork-latex footbed. Adjustable buckles for a perfect fit.",
    price: 110,
    images: ["image-1.jpg"],
    tags: ["Sandals", "Casual"],
    variants: [
      v("Brown", 37, 3),
      v("Brown", 38, 4),
      v("Brown", 39, 2),
      v("White", 37, 5),
      v("White", 38, 0),
      v("White", 39, 4),
    ],
  },
  {
    name: "Vans Old Skool Kids",
    brand: "Vans",
    gender: "kids",
    category: "Sneakers",
    description:
      "The classic side-stripe sneaker, sized for kids. Sturdy canvas and suede uppers, padded collar, signature waffle outsole.",
    price: 60,
    images: ["image-1.jpg"],
    tags: ["Sneakers"],
    variants: [
      v("Black", 30, 3),
      v("Black", 31, 4),
      v("Black", 32, 5),
      v("Red", 30, 2),
      v("Red", 31, 3),
      v("Red", 32, 0),
    ],
  },
];

export const sample_brands = [
  { name: "Nike", logoUrl: "" },
  { name: "Adidas", logoUrl: "" },
  { name: "Converse", logoUrl: "" },
  { name: "Asics", logoUrl: "" },
  { name: "Dr. Martens", logoUrl: "" },
  { name: "Timberland", logoUrl: "" },
  { name: "Clarks", logoUrl: "" },
  { name: "Birkenstock", logoUrl: "" },
  { name: "Vans", logoUrl: "" },
];

export const sample_colors = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Green", hex: "#2E7D32" },
  { name: "Blue", hex: "#1976D2" },
  { name: "Pink", hex: "#EC407A" },
  { name: "Grey", hex: "#9E9E9E" },
  { name: "Cream", hex: "#F5E6CA" },
  { name: "Cherry", hex: "#8B0000" },
  { name: "Wheat", hex: "#D2B48C" },
  { name: "Brown", hex: "#5C3A21" },
  { name: "Red", hex: "#D32F2F" },
];

export const sample_tags = [
  { name: "All", count: 10 },
  { name: "Sneakers", count: 4 },
  { name: "Running", count: 2 },
  { name: "Sport", count: 2 },
  { name: "Boots", count: 2 },
  { name: "Formal", count: 1 },
  { name: "Sandals", count: 1 },
  { name: "Casual", count: 5 },
];

export const sample_users = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
  {
    name: "James Doe",
    email: "james@gmail.com",
    password: "12345",
    address: "Tokyo",
    isAdmin: true,
  },
  {
    name: "Loan Doe",
    email: "loan@gmail.com",
    password: "12345",
    address: "Los Angeles",
    isAdmin: true,
  },
  {
    name: "Emily Smith",
    email: "emily@gmail.com",
    password: "12345",
    address: "New York",
    isAdmin: false,
  },
  {
    name: "Michael Johnson",
    email: "michael@gmail.com",
    password: "12345",
    address: "London",
    isAdmin: true,
  },
  {
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    password: "12345",
    address: "Sydney",
    isAdmin: false,
  },
  {
    name: "Alex Johnson",
    email: "alex@gmail.com",
    password: "12345",
    address: "Chicago",
    isAdmin: false,
  },
  {
    name: "Olivia Williams",
    email: "olivia@gmail.com",
    password: "12345",
    address: "Paris",
    isAdmin: false,
  },
  {
    name: "Ethan Brown",
    email: "ethan@gmail.com",
    password: "12345",
    address: "Berlin",
    isAdmin: true,
  },
];
