const v = (color, size, stock) => ({ color, size, stock });

export const sample_products = [
  {
    name: "Air Max 90",
    brand: "Nike",
    gender: "men",
    category: "Sneakers",
    description:
      "Iconic Air cushioning meets timeless street style. The Air Max 90 stays true to its OG running roots with the iconic Waffle sole, stitched overlays and classic TPU details.",
    price: 13000,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"],
    tags: ["Sneakers", "Casual"],
    variants: [
      v("Black", 41, 5),
      v("Black", 42, 8),
      v("Black", 43, 4),
      v("Black", 45, 0),
      v("White", 41, 6),
      v("White", 42, 3),
      v("White", 43, 7),
    ],
  },
  {
    name: "Stan Smith",
    brand: "Adidas",
    gender: "men",
    category: "Sneakers",
    description:
      "A clean court classic. The Stan Smith has stood the test of time as a minimalist tennis shoe turned everyday icon.",
    price: 10000,
    images: ["https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=600&q=80"],
    tags: ["Sneakers", "Casual"],
    variants: [
      v("White", 39, 4),
      v("White", 40, 6),
      v("White", 41, 5),
      v("White", 42, 7),
      v("Green", 40, 2),
      v("Green", 41, 0),
      v("Green", 42, 3),
    ],
  },
  {
    name: "Chuck 70",
    brand: "Converse",
    gender: "women",
    category: "Sneakers",
    description:
      "A premium take on the original Chuck Taylor. Higher-quality canvas, cushioned insole and vintage detailing.",
    price: 8500,
    images: ["https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600&q=80"],
    tags: ["Sneakers", "Casual"],
    variants: [
      v("Black", 37, 3),
      v("Black", 38, 5),
      v("Black", 39, 4),
      v("Cream", 37, 2),
      v("Cream", 38, 0),
      v("Cream", 39, 6),
    ],
  },
  {
    name: "Pegasus 40",
    brand: "Nike",
    gender: "men",
    category: "Running",
    description:
      "A workhorse running shoe with responsive React foam and dual Air Zoom units for a smooth, springy ride.",
    price: 14000,
    images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80"],
    tags: ["Running", "Sport"],
    variants: [
      v("Blue", 41, 4),
      v("Blue", 42, 6),
      v("Blue", 43, 3),
      v("Black", 41, 2),
      v("Black", 42, 5),
      v("Black", 43, 0),
    ],
  },
  {
    name: "Gel-Kayano 30",
    brand: "Asics",
    gender: "women",
    category: "Running",
    description:
      "Premium stability running shoe with FF BLAST PLUS ECO foam and PureGEL technology for a soft, supported run.",
    price: 16500,
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80"],
    tags: ["Running", "Sport"],
    variants: [
      v("Pink", 38, 3),
      v("Pink", 39, 4),
      v("Pink", 40, 2),
      v("Grey", 38, 5),
      v("Grey", 39, 6),
      v("Grey", 40, 4),
    ],
  },
  {
    name: "1460",
    brand: "Dr. Martens",
    gender: "men",
    category: "Boots",
    description:
      "The original 8-eye boot. Smooth leather, yellow welt stitch, and a Goodyear-welted air-cushioned sole.",
    price: 18000,
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80"],
    tags: ["Boots", "Casual"],
    variants: [
      v("Black", 40, 4),
      v("Black", 41, 5),
      v("Black", 42, 3),
      v("Cherry", 40, 2),
      v("Cherry", 41, 0),
      v("Cherry", 42, 4),
    ],
  },
  {
    name: "6-Inch Premium",
    brand: "Timberland",
    gender: "men",
    category: "Boots",
    description: "The original yellow boot. Waterproof premium leather, padded collar, seam-sealed construction.",
    price: 21000,
    images: ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80"],
    tags: ["Boots"],
    variants: [v("Wheat", 41, 3), v("Wheat", 42, 4), v("Wheat", 43, 2), v("Wheat", 44, 5)],
  },
  {
    name: "Tilden Cap Oxford",
    brand: "Clarks",
    gender: "men",
    category: "Formal",
    description: "A classic cap-toe oxford in polished leather. Cushioned footbed and rubber sole for all-day comfort.",
    price: 12000,
    images: ["https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600&q=80"],
    tags: ["Formal"],
    variants: [
      v("Black", 41, 4),
      v("Black", 42, 5),
      v("Black", 43, 3),
      v("Brown", 41, 2),
      v("Brown", 42, 4),
      v("Brown", 43, 0),
    ],
  },
  {
    name: "Arizona",
    brand: "Birkenstock",
    gender: "women",
    category: "Sandals",
    description:
      "Two-strap classic with the famous contoured cork-latex footbed. Adjustable buckles for a perfect fit.",
    price: 11000,
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&q=80"],
    tags: ["Sandals", "Casual"],
    variants: [
      v("Brown", 37, 3),
      v("Brown", 38, 4),
      v("Brown", 39, 2),
      v("White", 37, 5),
      v("White", 38, 0),
      v("White", 39, 4),
    ],
  },
  {
    name: "Old Skool Kids",
    brand: "Vans",
    gender: "kids",
    category: "Sneakers",
    description:
      "The classic side-stripe sneaker, sized for kids. Sturdy canvas and suede uppers, padded collar, signature waffle outsole.",
    price: 6000,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80"],
    tags: ["Sneakers"],
    variants: [
      v("Black", 30, 3),
      v("Black", 31, 4),
      v("Black", 32, 5),
      v("Red", 30, 2),
      v("Red", 31, 3),
      v("Red", 32, 0),
    ],
  },
  {
    name: "Court Pump",
    brand: "Clarks",
    gender: "women",
    category: "Formal",
    description:
      "A versatile leather court pump with a 50mm block heel and cushioned insole — office to evening without missing a beat.",
    price: 11500,
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80"],
    tags: ["Formal"],
    variants: [
      v("Black", 37, 4),
      v("Black", 38, 6),
      v("Black", 39, 5),
      v("Black", 40, 3),
      v("Nude", 37, 3),
      v("Nude", 38, 5),
      v("Nude", 39, 4),
    ],
  },
  {
    name: "Penny Loafer",
    brand: "Clarks",
    gender: "men",
    category: "Formal",
    description:
      "A timeless slip-on in supple leather. Hand-stitched apron, leather-lined footbed, and a hard-wearing rubber sole.",
    price: 13500,
    images: ["https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&q=80"],
    tags: ["Formal"],
    variants: [
      v("Brown", 41, 5),
      v("Brown", 42, 7),
      v("Brown", 43, 4),
      v("Burgundy", 41, 3),
      v("Burgundy", 42, 5),
      v("Burgundy", 43, 2),
    ],
  },
  {
    name: "Performance Slide",
    brand: "Adidas",
    gender: "men",
    category: "Sandals",
    description:
      "Cloud-soft sport slide with a contoured footbed. The post-game / pool-deck staple.",
    price: 4500,
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&q=80"],
    tags: ["Sandals", "Sport"],
    variants: [
      v("Black", 41, 6),
      v("Black", 42, 8),
      v("Black", 43, 5),
      v("Black", 44, 4),
      v("Blue", 42, 3),
      v("Blue", 43, 5),
    ],
  },
  {
    name: "Splash Sandal",
    brand: "Birkenstock",
    gender: "kids",
    category: "Sandals",
    description:
      "Adjustable hook-and-loop sandal built for the playground, the pool, and the trip back home.",
    price: 4000,
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&q=80"],
    tags: ["Sandals", "Casual"],
    variants: [
      v("Pink", 28, 4),
      v("Pink", 29, 5),
      v("Pink", 30, 4),
      v("Blue", 28, 3),
      v("Blue", 29, 5),
      v("Blue", 30, 4),
    ],
  },
  {
    name: "Jadon",
    brand: "Dr. Martens",
    gender: "women",
    category: "Boots",
    description:
      "The 1460 silhouette on a chunky platform sole. Smooth leather and yellow welt stitch with extra height and attitude.",
    price: 22000,
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80"],
    tags: ["Boots"],
    variants: [
      v("Black", 37, 4),
      v("Black", 38, 6),
      v("Black", 39, 5),
      v("Black", 40, 3),
    ],
  },
  {
    name: "Court Trainer Kids",
    brand: "Nike",
    gender: "kids",
    category: "Running",
    description:
      "A lightweight kid's runner with breathable mesh, a flexible foam midsole, and a hook-and-loop closure for solo lace-up wins.",
    price: 5500,
    images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80"],
    tags: ["Running", "Sport"],
    variants: [
      v("Blue", 30, 5),
      v("Blue", 31, 6),
      v("Blue", 32, 5),
      v("Blue", 33, 4),
      v("Pink", 30, 4),
      v("Pink", 31, 5),
      v("Pink", 32, 4),
    ],
  },
  {
    name: "Trailblazer Kids",
    brand: "Timberland",
    gender: "kids",
    category: "Boots",
    description:
      "A weatherproof leather boot for kids — padded collar, sturdy lugged sole, and the iconic premium upper.",
    price: 8500,
    images: ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80"],
    tags: ["Boots"],
    variants: [
      v("Wheat", 30, 3),
      v("Wheat", 31, 5),
      v("Wheat", 32, 4),
      v("Wheat", 33, 3),
    ],
  },
];

export const sample_brands = [
  { name: "Nike", logoUrl: "" },
  { name: "Adidas", logoUrl: "" },
  { name: "Converse", logoUrl: "" },
  { name: "Asics", logoUrl: "" },
  { name: "Dr. Martens", logoUrl: "" },
  { name: "Timberland", logoUrl: "" },
  { name: "Clarks", logoUrl: "" },
  { name: "Birkenstock", logoUrl: "" },
  { name: "Vans", logoUrl: "" },
];

export const sample_colors = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Green", hex: "#2E7D32" },
  { name: "Blue", hex: "#1976D2" },
  { name: "Pink", hex: "#EC407A" },
  { name: "Grey", hex: "#9E9E9E" },
  { name: "Cream", hex: "#F5E6CA" },
  { name: "Cherry", hex: "#8B0000" },
  { name: "Wheat", hex: "#D2B48C" },
  { name: "Brown", hex: "#5C3A21" },
  { name: "Red", hex: "#D32F2F" },
  { name: "Nude", hex: "#E8C5A8" },
  { name: "Burgundy", hex: "#7A1F2B" },
];

export const sample_tags = [
  { name: "All", count: 10 },
  { name: "Sneakers", count: 4 },
  { name: "Running", count: 2 },
  { name: "Sport", count: 2 },
  { name: "Boots", count: 2 },
  { name: "Formal", count: 1 },
  { name: "Sandals", count: 1 },
  { name: "Casual", count: 5 },
];

export const sample_users = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
  {
    name: "James Doe",
    email: "james@gmail.com",
    password: "12345",
    address: "Tokyo",
    isAdmin: true,
  },
  {
    name: "Loan Doe",
    email: "loan@gmail.com",
    password: "12345",
    address: "Los Angeles",
    isAdmin: true,
  },
  {
    name: "Emily Smith",
    email: "emily@gmail.com",
    password: "12345",
    address: "New York",
    isAdmin: false,
  },
  {
    name: "Michael Johnson",
    email: "michael@gmail.com",
    password: "12345",
    address: "London",
    isAdmin: true,
  },
  {
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    password: "12345",
    address: "Sydney",
    isAdmin: false,
  },
  {
    name: "Alex Johnson",
    email: "alex@gmail.com",
    password: "12345",
    address: "Chicago",
    isAdmin: false,
  },
  {
    name: "Olivia Williams",
    email: "olivia@gmail.com",
    password: "12345",
    address: "Paris",
    isAdmin: false,
  },
  {
    name: "Ethan Brown",
    email: "ethan@gmail.com",
    password: "12345",
    address: "Berlin",
    isAdmin: true,
  },
];
